### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Hitgub01** [blocktrail/wallet-recovery-tool#17]
Hello when i wan't to recover my bitcoin ik get an error something about a string???

**Comment by jiangjinyuan** [comment]
@Hitgub01 Can you describe the error in more detail, is there a log?

**Comment by Hitgub01** [comment]
> @Hitgub01 Can you describe the error in more detail, is there a log?

i get an error something about string.

**Comment by jiangjinyuan** [comment]
pls paste the error info...

> > @Hitgub01 Can you describe the error in more detail, is there a log?
> 
> i get an error something about string.

**Comment by Hitgub01** [comment]
Hello i'm looking for some people to reinforce my team, do you know some people who has experiance in develop...,design...

**Comment by Engareh** [comment]
hi, I do whatever you said but when I run serve I got error bellow:
C:\Users\Hamid\AppData\Roaming\npm\node_modules\serve\build>serve
C:\Users\Hamid\AppData\Roaming\npm\node_modules\serve\build\main.js:4
import { cwd as getPwd, exit, env as env2, stdout } from "node:process";
       ^

SyntaxError: Unexpected token {
    at new Script (vm.js:79:7)
    at createScript (vm.js:251:10)
    at Object.runInThisContext (vm.js:303:10)
    at Module._compile (internal/modules/cjs/loader.js:657:28)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:742:12)
    at startup (internal/bootstrap/node.js:283:19)
